/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/hibernate/DAOHibernate.e.vm.java
 */
package com.bizintelapps.zytoon.dao;

import org.hibernate.Criteria;
import org.hibernate.criterion.Restrictions;
import org.springframework.stereotype.Repository;
import com.bizintelapps.zytoon.dao.hibernate.HibernateUtil;
import com.bizintelapps.zytoon.dao.support.SearchTemplate;

import com.bizintelapps.zytoon.domain.Authorities;
import com.bizintelapps.zytoon.dao.hibernate.HibernateGenericDao;

/**
 * Hibernate implementation of the Authorities DAO interface.
 */
@Repository
public class AuthoritiesDaoImpl extends HibernateGenericDao<Authorities, Integer> implements AuthoritiesDao {
    public AuthoritiesDaoImpl() {
        super(Authorities.class);
    }

    /**
     * Constructs the search by example criteria using not only the passed authorities but also its associated entities. 
     */
    @Override
    public Criteria getCriteria(Authorities authorities, SearchTemplate searchTemplate) {
        // Call super to construct the criteria of the 'root' entity.
        Criteria criteria = super.getCriteria(authorities, searchTemplate);

        // many-to-one: "users"
        // Note 1: If 'username' != null, no need to add a criteria as the current criteria 
        // already takes this property into account.
        // Note 2: By convention, if the example for "users" has no property set 
        // and "users" is not null we assume that you want a not null criteria. 
        if (authorities.getUsername() == null && authorities.getUsers() != null) {
            criteria.add(Restrictions.isNotNull("users"));
            criteria.createCriteria("users")
                    .add(HibernateUtil.constructExample(authorities.getUsers(), searchTemplate));
        }

        return criteria;
    }
}