/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/hibernate/DAOHibernate.e.vm.java
 */
package com.bizintelapps.zytoon.dao;

import java.util.List;
import org.springframework.stereotype.Repository;

import com.bizintelapps.zytoon.dao.hibernate.HibernateGenericDao;
import com.bizintelapps.zytoon.domain.Message;
import java.util.ArrayList;

/**
 * Hibernate implementation of the UserProfile DAO interface.
 */
@Repository
public class MessageDaoImpl extends HibernateGenericDao<Message, Integer> implements MessageDao {

    public MessageDaoImpl() {
        super(Message.class);
    }

    @Override
    public List<Message> findUnread(Integer userId, int first, int max) {
        List<Message> list = null;
        try {

            list = this.getEntityManager().createNamedQuery("Message.findUnread").setParameter("id", userId).setFirstResult(first).setMaxResults(max).getResultList();
        } catch (RuntimeException re) {
            list = new ArrayList<Message> ();
        }

        return list;
    }
}