/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/hibernate/DAOHibernate.e.vm.java
 */
package com.bizintelapps.zytoon.dao;

import java.util.List;
import org.springframework.stereotype.Repository;

import com.bizintelapps.zytoon.domain.ProgramStructure;
import com.bizintelapps.zytoon.dao.hibernate.HibernateGenericDao;

/**
 * Hibernate implementation of the ProgramStructure DAO interface.
 */
@Repository
public class ProgramStructureDaoImpl extends HibernateGenericDao<ProgramStructure, Integer> implements
        ProgramStructureDao {
    public ProgramStructureDaoImpl() {
        super(ProgramStructure.class);
    }

    @Override
    public List<ProgramStructure> ProgramStructureByDayOfWeekAndMonth(Integer dayOfWeek, Integer dayOfMonth) {
        List<ProgramStructure> list = null;
        list = this.getEntityManager().createNamedQuery("ProgramStructure.ProgramStructureByDayOfWeekAndMonth", ProgramStructure.class)
                .setParameter("dayOfWeek", dayOfWeek)
                .setParameter("dayOfMonth", dayOfMonth)
                .getResultList();
        return list;
    }

    @Override
    public List<ProgramStructure> findAll() {
        return this.getEntityManager().createNamedQuery("ProgramStructure.findAll")
                .getResultList();
    }
}