/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/dao/DAO.e.vm.java
 */
package com.bizintelapps.zytoon.dao;

import com.bizintelapps.zytoon.dao.support.GenericDao;
import com.bizintelapps.zytoon.domain.Program;
import java.util.List;
import java.util.Date;

/**
 * DAO Interface for {@link Program}
 */
public interface ProgramDao extends GenericDao<Program, Integer> {
    
    List<Program> findByStatus(String username);
    
    void updateExpiredPrograms(Date date);
    
    Program findById(Integer programId);
}
