/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/dao/DAO.e.vm.java
 */
package com.bizintelapps.zytoon.dao;

import java.util.List;
import com.bizintelapps.zytoon.dao.support.GenericDao;
import com.bizintelapps.zytoon.domain.ProgramStructure;

/**
 * DAO Interface for {@link ProgramStructure}
 */
public interface ProgramStructureDao extends GenericDao<ProgramStructure, Integer> {
    
    public List<ProgramStructure> ProgramStructureByDayOfWeekAndMonth(Integer dayOfWeek, Integer dayOfMonth);

    public List<ProgramStructure> findAll();
}
