/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/dao/DAO.e.vm.java
 */
package com.bizintelapps.zytoon.dao;

import com.bizintelapps.zytoon.dao.support.GenericDao;
import com.bizintelapps.zytoon.domain.SalahMonthly;
import com.bizintelapps.zytoon.domain.SalahDaily;
import com.bizintelapps.zytoon.domain.UserProfile;
import java.util.List;

/**
 * DAO Interface for {@link UserProfile}
 */
public interface SalahMonthlyDao extends GenericDao<SalahMonthly, Integer> {
    
    SalahMonthly findByUserAndDate(Integer userId, Integer month, Integer year);
    List<SalahMonthly> findAllByUserAndDate(Integer userId, Integer month, Integer year);
    List<SalahDaily> findDailyByUserAndDate(Integer userId, Integer month, Integer year);
}
