/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/hibernate/DAOHibernate.e.vm.java
 */
package com.bizintelapps.zytoon.dao;

import com.bizintelapps.zytoon.domain.SalahDaily;
import java.util.List;
import org.springframework.stereotype.Repository;

import com.bizintelapps.zytoon.dao.hibernate.HibernateGenericDao;
import java.util.ArrayList;
import org.apache.log4j.Logger;

/**
 * Hibernate implementation of the UserProfile DAO interface.
 */
@Repository
public class SalahDailyDaoImpl extends HibernateGenericDao<SalahDaily, Integer> implements SalahDailyDao {
    public SalahDailyDaoImpl() {
        super(SalahDaily.class);
    }
    
    @SuppressWarnings("unused")
    private static final Logger logger = Logger.getLogger(FoodDailyDaoImpl.class);

    @Override
    public List findDailyByUser(Integer userBasicId) {
        List list = null;
        try {
            list = getEntityManager().createNamedQuery("SalahDaily.findDailyByUser")
                    .setParameter("userId", userBasicId)
                    .getResultList();
        } catch (RuntimeException re){
            logger.warn(re.getMessage(), re);
            list = new ArrayList();
        }
        return list;
    }

   
}