/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/dao/DAO.e.vm.java
 */
package com.bizintelapps.zytoon.dao;

import com.bizintelapps.zytoon.dao.support.GenericDao;
import com.bizintelapps.zytoon.domain.UserNetwork;
import com.bizintelapps.zytoon.domain.Users;
import java.util.List;

/**
 * DAO Interface for {@link Users}
 */
public interface UserNetworkDao extends GenericDao<UserNetwork, Integer> {
    
    List<UserNetwork> findByUserBasicId(String username);
    UserNetwork findByUserAndFriend ( Integer user, Integer friend);
}
