/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/hibernate/DAOHibernate.e.vm.java
 */
package com.bizintelapps.zytoon.dao;

import org.springframework.stereotype.Repository;

import com.bizintelapps.zytoon.dao.hibernate.HibernateGenericDao;
import com.bizintelapps.zytoon.domain.UserNetwork;
import java.util.ArrayList;
import java.util.List;

/**
 * Hibernate implementation of the Users DAO interface.
 */
@Repository
public class UserNetworkDaoImpl extends HibernateGenericDao<UserNetwork, Integer> implements UserNetworkDao {

    public UserNetworkDaoImpl() {
        super(UserNetwork.class);
    }

    @Override
    public List<UserNetwork> findByUserBasicId(String username) {
        List<UserNetwork> list = null;
        try {
            list = getEntityManager().createNamedQuery("UserNetwork.findByUserBasicId", UserNetwork.class)
                    .setParameter("username", username)
                    .getResultList();
        } catch (RuntimeException re) {
            list = new ArrayList<UserNetwork>();
        }
        return list;
    }

    @Override
    public UserNetwork findByUserAndFriend(Integer user, Integer friend) {
        UserNetwork un = null;
        try {
            un = getEntityManager().createNamedQuery("UserNetwork.findByUserAndFriend", UserNetwork.class)
                    .setParameter("user", user)
                    .setParameter("friend", friend)
                    .getSingleResult();
        } catch (RuntimeException re ) {}
        return un;
    }
}