/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/hibernate/DAOHibernate.e.vm.java
 */
package com.bizintelapps.zytoon.dao;

import java.util.ArrayList;
import java.util.List;
import org.hibernate.criterion.Criterion;
import org.springframework.stereotype.Repository;
import com.bizintelapps.zytoon.dao.hibernate.HibernateUtil;
import com.bizintelapps.zytoon.dao.support.SearchTemplate;

import com.bizintelapps.zytoon.domain.Users;
import com.bizintelapps.zytoon.dao.hibernate.HibernateGenericDao;

/**
 * Hibernate implementation of the Users DAO interface.
 */
@Repository
public class UsersDaoImpl extends HibernateGenericDao<Users, String> implements UsersDao {
    public UsersDaoImpl() {
        super(Users.class);
    }

    /**
     * Add criterion so the primary key is 
     * included in a search by example.
     */
    @Override
    protected List<Criterion> getByExampleExtraCriterions(Users model, SearchTemplate searchTemplate) {
        List<Criterion> criterions = new ArrayList<Criterion>();

        // handle pk fields
        if (model.isPrimaryKeySet() && model.getUsername().length() > 0) {
            criterions.add(HibernateUtil.constructPatternCriterion("username", model.getPrimaryKey(), searchTemplate));
        }
        return criterions;
    }

    @Override
    public Users findByUsername(String email) {
        Users user = null;
        
        try {
            user = this.getEntityManager().createNamedQuery("Users.findByUsername", Users.class)
                .setParameter("username", email)
                .getSingleResult();
        } catch (RuntimeException ex) {
            
        }
        return user;
    }
}