/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/hibernate/DAOHibernate.e.vm.java
 */
package com.bizintelapps.zytoon.dao;

import org.springframework.stereotype.Repository;
import com.bizintelapps.zytoon.dao.UserProfileDao;

import com.bizintelapps.zytoon.domain.UserProfile;
import com.bizintelapps.zytoon.dao.hibernate.HibernateGenericDao;

/**
 * Hibernate implementation of the UserProfile DAO interface.
 */
@Repository
public class UserProfileDaoImpl extends HibernateGenericDao<UserProfile, Integer> implements UserProfileDao {
    public UserProfileDaoImpl() {
        super(UserProfile.class);
    }

    @Override
    public UserProfile findByUsername(String username) {
        return this.getEntityManager().createNamedQuery("UserProfile.findByUsername", UserProfile.class)
                .setParameter("username", username)
                .getSingleResult();
    }
}