/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/dao/DAO.e.vm.java
 */
package com.bizintelapps.zytoon.dao;

import com.bizintelapps.zytoon.dao.support.GenericDao;
import com.bizintelapps.zytoon.domain.Program;
import com.bizintelapps.zytoon.domain.UserEnrollment;
import com.bizintelapps.zytoon.domain.UserProfile;
import java.util.Date;
import java.util.List;

/**
 * DAO Interface for {@link UserEnrollment}
 */
public interface UserEnrollmentDao extends GenericDao<UserEnrollment, Integer> {
    
    List<UserEnrollment> findByActiveAndNotDueAndReportDate(Boolean isActive, Boolean isDue, Date reportDate);
    
    List<UserEnrollment> findDueEnrollments(Integer userId);
    
    List<UserProfile> findUserByDueEnrollmentAndDate(Date date);
    
    List<UserProfile> findByInactivity(Date date);
    
    List<Program> findActivePrograms(String username);
}
