/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/hibernate/DAOHibernate.e.vm.java
 */
package com.bizintelapps.zytoon.dao;

import org.hibernate.Criteria;
import org.hibernate.criterion.Restrictions;
import org.springframework.stereotype.Repository;
import com.bizintelapps.zytoon.dao.hibernate.HibernateUtil;
import com.bizintelapps.zytoon.dao.support.SearchTemplate;

import com.bizintelapps.zytoon.domain.UserGraduation;
import com.bizintelapps.zytoon.dao.hibernate.HibernateGenericDao;

/**
 * Hibernate implementation of the UserGraduation DAO interface.
 */
@Repository
public class UserGraduationDaoImpl extends HibernateGenericDao<UserGraduation, Integer> implements UserGraduationDao {
    public UserGraduationDaoImpl() {
        super(UserGraduation.class);
    }

    /**
     * Constructs the search by example criteria using not only the passed userGraduation but also its associated entities. 
     */
    @Override
    public Criteria getCriteria(UserGraduation userGraduation, SearchTemplate searchTemplate) {
        // Call super to construct the criteria of the 'root' entity.
        Criteria criteria = super.getCriteria(userGraduation, searchTemplate);

        // many-to-one: "user"
        // Note 1: If 'userId' != null, no need to add a criteria as the current criteria 
        // already takes this property into account.
        // Note 2: By convention, if the example for "user" has no property set 
        // and "user" is not null we assume that you want a not null criteria. 
        if (userGraduation.getUserId() == null && userGraduation.getUser() != null) {
            criteria.add(Restrictions.isNotNull("user"));
            criteria.createCriteria("user").add(
                    HibernateUtil.constructExample(userGraduation.getUser(), searchTemplate));
        }

        // many-to-one: "programStructure"
        // Note 1: If 'programStructureId' != null, no need to add a criteria as the current criteria 
        // already takes this property into account.
        // Note 2: By convention, if the example for "programStructure" has no property set 
        // and "programStructure" is not null we assume that you want a not null criteria. 
        if (userGraduation.getProgramStructureId() == null && userGraduation.getProgramStructure() != null) {
            criteria.add(Restrictions.isNotNull("programStructure"));
            criteria.createCriteria("programStructure").add(
                    HibernateUtil.constructExample(userGraduation.getProgramStructure(), searchTemplate));
        }

        return criteria;
    }
}