<%--
 | (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 | Source code generated by Celerio, a Jaxio product
 | Want to use Celerio within your company? email us at info@jaxio.com
 | Follow us on twitter: @springfuse
 | Template pack-mvc-3:src/main/webapp/WEB-INF/views/login/index.p.vm.jsp
--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="tags" tagdir="/WEB-INF/tags"%>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>

<div data-role="page" data-theme="a" >

    <div data-role="header" >
        <h1>Login</h1>
        <div id="fb-root"></div>
        <script type='text/javascript' src='${pageContext.request.contextPath}/dwr/engine.js'></script>    
        <script type='text/javascript' src='${pageContext.request.contextPath}/dwr/interface/GeneralAjaxService.js'></script>
        <script type='text/javascript'>
            window.fbAsyncInit = function() {
                FB.init({
                    appId      : '154023078029672',
                    status     : true, 
                    cookie     : true,
                    xfbml      : true,
                    oauth      : true
                });
                /* All the events registered */
                FB.Event.subscribe('auth.login', function (response) {
                    if (response.status == 'connected' ) {
                        verify(response)
                    }
                });
                //FB.logout()
            };
            (function(d){
                var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
                js = d.createElement('script'); js.id = id; js.async = true;
                js.src = "https://connect.facebook.net/en_US/all.js";
                d.getElementsByTagName('head')[0].appendChild(js);
            }(document));
            var code = 0;
            function verify(response){
                GeneralAjaxService.fbAccessToken(response.authResponse.accessToken, code, function(c) {
                    code = c
                    if ( code == -1 ){
                        FB.login()
                    } else if ( code == 1) {
                        window.location.href = "/home/index";
                    } else {
                        alert ("Error authenticating credentials, please try again!")
                    }
                })
            }
            $(document).ready(function() {
                if ( window.location.href.indexOf("www") == -1 )
                    window.location.href = "http://www.zytoon.me"
                
                $("#fb-login").click("tap", function(){
                    FB.getLoginStatus(function (response) {
                        if (response.status == 'connected' ) {
                            verify(response)
                        } 
                    });
                })
                $("#fb-login").dblclick(function(){
                    
                })
                var hash = window.location.hash
                if ( hash.length > 0 ) {
                    window.location.href = "/login/index";
                }
            })
        </script>
    </div>
    <div data-role="content" >

        <div class="container" style="width: 300px">

            <c:if test="${not empty SPRING_SECURITY_LAST_USERNAME}">
                Invalid login!
            </c:if>

            <c:url value="/logincheck" var="loginUrl" />
            <form action="${loginUrl}" modelAttribute="loginForm" method="post" data-ajax="false">
                <fieldset>
                    <div class="input-div">
                        <input type="text" name="j_username" value="${SPRING_SECURITY_LAST_USERNAME}" placeholder=" Email"/>
                    </div>
                    <div class="input-div">
                        <input type="password" name="j_password" placeHolder=" Password " />
                    </div>
                    <div class="input-div" class="full" >
                        <input type="submit" data-role="button" class="full" data-theme="b" data-icon="check" data-inline="true" value="<fmt:message key="login.submit" />" />
                    </div>
                    <%--
                    <div data-role="fieldcontain" class="ui-hide-label">
                        <label for="j_username">Email:</label>
                        <input type="text" name="j_username" value="${SPRING_SECURITY_LAST_USERNAME}" placeholder=" Email"/>
                    </div>
                    <div data-role="fieldcontain" class="ui-hide-label">
                        <label for="j_password">Password</label><br/>
                        <input type="password" name="j_password" placeHolder=" Password " />
                    </div>
                    <div style="display: none">
                        <checkbox id="rememberme" name="_spring_security_remember_me" checked="checked" />
                    </div>
                    <div data-inline="true">
                        <input type="submit" data-role="button" data-theme="b" data-icon="check" data-inline="true" value="<fmt:message key="login.submit" />" />
                    </div>
                    
                    <p>
                        <fmt:message key="login.username" />
                        <br />
                        <form:input path="j_username" cssClass="required" />
                        <form:errors cssClass="error" path="j_username" />
                    </p>
                    <p>
                        <fmt:message key="login.password" />
                        <br />
                        <form:password path="j_password" cssClass="required" />
                    </p>
                    <p>
                        <fmt:message key="login.rememberme" />
                        <br />
                        <form:checkbox id="rememberme" path="_spring_security_remember_me" />
                    </p>
                    <p>
                        <input type="submit" class="button button-login" value="<fmt:message key="login.submit" />"/>
                    </p>
                    --%>

                </fieldset>
            </form>
            <fb:login-button id="fb-login" autologoutlink="true" scope="email" size="large" length="long">Log In with Facebook</fb:login-button>
        </div>

    </div>
    <div data-role="footer" data-position="fixed">
        <div data-role="navbar">
            <ul>
                <li><a href="pr"  rel="external" data-role="button" data-icon="back" data-inline="true" data-theme="a">Forgot Password</a></li>
                <li><a href="/login/register" data-role="button" data-icon="plus" data-iconpos="left" data-inline="true" rel="external"  data-theme="a">Sign Up</a></li>
            </ul>
        </div>
        <div data-role="navbar" data-position="fixed">
            <ul>
                <li><a href="javascript:void(0);" >@Zytoon.me</a></li>
            </ul>
        </div>
    </div><!-- /footer -->
</div>

