/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/web/controller/admin/AdminForm.p.vm.java
 */
package com.bizintelapps.zytoon.web.controller.admin;

public class AdminForm {

    private String exceptionName;
    private String[] exceptionsList = new String[] { "java.lang.Exception", "java.lang.RuntimeException",
            "org.hibernate.HibernateException", "org.hibernate.ObjectNotFoundException",
            "org.springframework.dao.ConcurrencyFailureException",
            "org.springframework.dao.DataAccessResourceFailureException",
            "org.springframework.dao.DataRetrievalFailureException",
            "org.springframework.dao.DeadlockLoserDataAccessException",
            "org.springframework.dao.PermissionDeniedDataAccessException" };

    public void setExceptionName(String exceptionName) {
        this.exceptionName = exceptionName;
    }

    public String getExceptionName() {
        return exceptionName;
    }

    public String[] getExceptionsList() {
        return exceptionsList;
    }
}