/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/web/validation/impl/package-info.p.vm.java
 */
/**
 * Implementation of the {@link javax.validation.Constraint} 
 */
package com.bizintelapps.zytoon.validation.impl;

