/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/formatter/support/DefaultEnumFormatter.p.vm.java
 */
package com.bizintelapps.zytoon.formatter.support;

import java.text.ParseException;
import java.util.Locale;

import org.springframework.context.MessageSource;
import org.springframework.format.Formatter;

@SuppressWarnings("rawtypes")
public class DefaultEnumFormatter implements Formatter<Enum<?>> {

    private final Class type;
    private final MessageSource messageSource;

    public DefaultEnumFormatter(Class type, MessageSource messageSource) {
        this.type = type;
        this.messageSource = messageSource;
    }

    public Class<?> getTarget() {
        return type;
    }

    public String print(Enum<?> value, Locale locale) {
        if (value == null) {
            return "";
        }
        return messageSource.getMessage(value.getClass().getSimpleName() + "_" + value.name(), null, locale);
    }

    @SuppressWarnings("unchecked")
    public Enum<?> parse(String text, Locale locale) throws ParseException {
        if (text == null || text.isEmpty()) {
            return null;
        }
        return Enum.valueOf(type, text);
    }
}
