/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/formatter/support/EnumFormatterAnnotationFactory.p.vm.java
 */
package com.bizintelapps.zytoon.formatter.support;

import java.text.ParseException;
import java.util.Collections;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.MessageSource;
import org.springframework.format.AnnotationFormatterFactory;
import org.springframework.format.Parser;
import org.springframework.format.Printer;
import org.springframework.stereotype.Component;

import com.bizintelapps.zytoon.formatter.EnumFormatter;

/**
 * Use the {@link AnnotationFormatterFactory} to build a generic {@link Formatter} for all methods or fields that have the {@link EnumFormater} annotation.
 * 
 * <pre>
 * &#064;EnumFormatter
 * public SpecificEnum getValue() {
 *     //
 * }
 * </pre>
 * 
 * @see EnumFormatter
 * @see AnnotationFormatterFactory
 * @see http://static.springsource.org/spring/docs/3.0.x/spring-framework-reference/html/validation.html#format-CustomFormatAnnotations
 */
@Component
public class EnumFormatterAnnotationFactory implements AnnotationFormatterFactory<EnumFormatter> {

    @Autowired
    private MessageSource messageSource;

    private final Set<Class<?>> fieldTypes;

    public EnumFormatterAnnotationFactory() {
        Set<Class<?>> rawFieldTypes = new HashSet<Class<?>>();
        rawFieldTypes.add(Enum.class);
        this.fieldTypes = Collections.unmodifiableSet(rawFieldTypes);
    }

    @Override
    public Set<Class<?>> getFieldTypes() {
        return fieldTypes;
    }

    @Override
    public Parser<?> getParser(EnumFormatter annotation, Class<?> fieldType) {
        return new DefaultEnumFormatter(fieldType, messageSource);
    }

    @Override
    public Printer<?> getPrinter(EnumFormatter annotation, Class<?> fieldType) {
        return new DefaultEnumFormatter(fieldType, messageSource);
    }
}
