<%--
 | (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 | Source code generated by Celerio, a Jaxio product
 | Want to use Celerio within your company? email us at info@jaxio.com
 | Follow us on twitter: @springfuse
 | Template pack-mvc-3:src/main/webapp/WEB-INF/views/index.p.vm.jsp
--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="tags" tagdir="/WEB-INF/tags"%>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<style>
    #xcontestHeader{padding-left: 11%;}
    #prizeList{padding-left: 3%;}
</style>

<div data-role="page" data-theme="a" >

    <div data-role="header">
        <h1>Zytoon.me - Beta 3</h1>
        <div id="fb-root"></div>
        <script type='text/javascript' src='${pageContext.request.contextPath}/dwr/engine.js'></script>    
        <script type='text/javascript' src='${pageContext.request.contextPath}/dwr/interface/GeneralAjaxService.js'></script>
        <script type='text/javascript'>
            window.fbAsyncInit = function() {
                FB.init({
                    appId      : '154023078029672',
                    status     : true, 
                    cookie     : true,
                    xfbml      : true,
                    oauth      : true
                });
                /* All the events registered */
                FB.Event.subscribe('auth.login', function (response) {
                    if (response.status == 'connected' ) {
                        verify(response)
                    }
                });
                //FB.logout()
            };
            (function(d){
                var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
                js = d.createElement('script'); js.id = id; js.async = true;
                js.src = "https://connect.facebook.net/en_US/all.js";
                d.getElementsByTagName('head')[0].appendChild(js);
            }(document));
            var code = 0;
            function verify(response){
                GeneralAjaxService.fbAccessToken(response.authResponse.accessToken, code, function(c) {
                    code = c
                    if ( code == -1 ){
                        FB.login()
                        //$("#fb-login").click()
                    } else if ( code == 1) {
                        window.location.href = "/home/index";
                    } else {
                        alert ("Error authenticating credentials, please try again!")
                    }
                })
            }
            $(document).ready(function() {
                if ( window.location.href.indexOf("www") == -1 )
                    window.location.href = "http://www.zytoon.me"
                
                $("#fb-login").click("tap", function(){
                    FB.getLoginStatus(function (response) {
                        if (response.status == 'connected' ) {
                            verify(response)
                        } 
                    });
                })
                $("#fb-login").dblclick(function(){
                    
                })
            })
        </script>
        <div data-role="navbar">
            <ul>
                <security:authorize ifAllGranted="ROLE_USER">
                    <jsp:forward page="/home/index" /> 
                </security:authorize>
            </ul>
        </div>
    </div>

    <div data-role="content" style="clear: both;word-wrap: break-word;">
        <div style="padding:10%;width:60%" class="container">
            <div style="text-align:right;">
                <fb:login-button id="fb-login" autologoutlink="true" scope="email" >Log In with Facebook</fb:login-button>
            </div>
            <br>
            <h2>  Awesome Network for Muslim Individuals, Families & Schools. </h2>
            <p style="text-align:center">  Track, compete and improve - Salaah, Adaab, History and Leadership! </p>
            <%--
            <div style="font-size:88%;">
                <p>There is always a scope for each person to improve their Salaah.</p>
                <ul>
                    <li>A person praying five times in a Masjid can take their Salaah to the next level and also pray Tahajjud and then retain it for life insha Allah.</li>
                    <li>Another person who only gets a chance to pray Jummah can start praying little more and improve from there.</li>

                </ul>
                <p>Zytoon.me helps achieve this!</p>
            </div>
            <br/>
            <br/>
            --%>
            <%-- <a href="${pageContext.request.contextPath}/login/winner1" data-role="button" data-icon="star" data-theme="a" rel ="external" style="width:300px">HP TouchPad Winner Announced!</a> --%>
            <br> 
            <p style="text-align:center; font-size: 80%"><br/>-- Introducing Healthy Eating Adaab Program ! </p>

            <br>
            <div style="text-align:center;">
                <a href="/login/video" data-rel="dialog">Demo</a> 
                &nbsp;&nbsp; | &nbsp;&nbsp;
                <a href="/home/index" rel="external" >Login</a>
            </div>
        </div>        
    </div>

    <div data-role="footer" data-position="fixed" class="" style="text-align: center;">
        <div data-role="navbar" data-position="fixed">
            <a href="http://www.bizintelapps.com" rel="external" target="_blank" style="width:200px">2011 ©BizIntelApps</a>
            &nbsp;<a href="mailto:team@zytoon.me" style="width:100px">Email us</a>
        </div>
    </div>
</div>

