/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/converter/DateConverter.p.vm.java
 */
package com.bizintelapps.zytoon.util;

import java.util.Date;

import org.joda.time.DateTime;
import org.joda.time.format.DateTimeFormat;
import org.joda.time.format.DateTimeFormatter;
import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;

/**
 *  Simple {@link Date} {@link Converter} with sensible defaults
 *  @see Converter
 */
@Component
public class DateConverter implements Converter<String, Date> {

    private DateTimeFormatter parser1 = DateTimeFormat.forPattern("dd-MMM-yyyy");

    private DateTimeFormatter parser2 = DateTimeFormat.forPattern("yyyy-MM-dd");

    @Override
    public Date convert(String text) {
        Date date = getDate(parser1, text);
        if (date != null) {
            return date;
        }
        return getDate(parser2, text);
    }

    private Date getDate(DateTimeFormatter parser, String text) {
        try {
            return parser.parseDateTime(text).toDate();
        } catch (Exception e) {
            return null;
        }
    }
}