/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/domain/Entity.e.vm.java
 */
package com.bizintelapps.zytoon.domain;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlTransient;
import org.apache.log4j.Logger;
import org.hibernate.validator.constraints.Length;
import com.bizintelapps.zytoon.validation.JpaUnique;
import java.util.Date;
import javax.persistence.GeneratedValue;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.springframework.format.annotation.DateTimeFormat;
import static javax.persistence.TemporalType.DATE;
import static com.bizintelapps.zytoon.util.ResourcesUtil.DATE_FORMAT_PATTERN;

@Entity
@Table(name = "track_ip")
@JpaUnique
public class TrackIP implements Identifiable<Integer>, Serializable {

    private static final long serialVersionUID = 1L;
    private static final Logger logger = Logger.getLogger(TrackIP.class);
    // Raw attributes
    private Integer id; // pk
    private String entity; // table
    private Integer entityId; // entity id
    private String action; // c - create, r - read, u - update, d - delete
    private String ip;
    private Date date;

    // ---------------------------
    // Constructors
    // ---------------------------
    public TrackIP() {
    }

    public TrackIP(Integer primaryKey) {
        this();
        setPrimaryKey(primaryKey);
    }

    public TrackIP(String entity, Integer entityId, String action, String ip) {
        this.entity = entity;
        this.entityId = entityId;
        this.action = action;
        this.ip = ip;
        this.date = new Date();
    }

    // ---------------------------
    // Identifiable implementation
    // ---------------------------
    @Transient
    @XmlTransient
    @Override
    public Integer getPrimaryKey() {
        return getId();
    }

    @Override
    public void setPrimaryKey(Integer id) {
        setId(id);
    }

    @Transient
    @XmlTransient
    @Override
    public boolean isPrimaryKeySet() {
        return isIdSet();
    }

    // -------------------------------
    // Getter & Setter
    // -------------------------------
    @Column(nullable = false, unique = true, precision = 10)
    @GeneratedValue
    @Id
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @NotNull
    @Length(max = 2)
    @Column(name = "action_", nullable = false, length = 2)
    public String getAction() {
        return action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    @NotNull
    @Length(max = 20)
    @Column(nullable = false, length = 20)
    public String getEntity() {
        return entity;
    }

    public void setEntity(String entity) {
        this.entity = entity;
    }

    @NotNull
    @Column(name = "entity_id", nullable = false)
    public Integer getEntityId() {
        return entityId;
    }

    public void setEntityId(Integer entityId) {
        this.entityId = entityId;
    }

    @NotNull
    @Length(max = 20)
    @Column(nullable = false, length = 20)
    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    @Transient
    public boolean isIdSet() {
        return id != null;
    }

    @Column(name = "date_", length = 10)
    @Temporal(TemporalType.TIMESTAMP)
    @DateTimeFormat(pattern = DATE_FORMAT_PATTERN)
    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    // -----------------------------------------
    // Set defaults values
    // -----------------------------------------
    /**
     * Set the default values.
     */
    public void initDefaultValues() {
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TrackIP other = (TrackIP) obj;
        if (this.id != other.id && (this.id == null || !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 47 * hash + (this.id != null ? this.id.hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "TrackIP{" + "id=" + id + '}';
    }
}