/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/web/util/SearchForm.p.vm.java
 */
package com.bizintelapps.zytoon.web.util;

import java.io.Serializable;
import java.util.List;
import java.util.ArrayList;

import static com.bizintelapps.zytoon.web.util.NullRestriction.NullRestrictionKind.IS_NOT_NULL;
import static com.bizintelapps.zytoon.web.util.NullRestriction.NullRestrictionKind.IS_NULL;
import static org.hibernate.criterion.Restrictions.isNull;
import static org.hibernate.criterion.Restrictions.isNotNull;

import com.bizintelapps.zytoon.dao.support.DateRange;
import com.bizintelapps.zytoon.dao.support.SearchTemplate;

/**
 * Holds informations to be displayed and filled by the spring mvc {@link Controller}.
 * <p>
 * This class return its information as a {@link SearchTemplate} that will be consummed by the {@link GenericEntityService}
 */
public class SearchForm implements Serializable {
    private static final long serialVersionUID = 1L;
    private SearchParameters searchParameters = new SearchParameters();

    /**
     * @return the {@link SearchParameters} controlling search meta attributes (order, pagination, etc.)
     */
    public SearchParameters getSp() {
        return searchParameters;
    }

    /**
     * Override it in subclass in order to provide specific {@link DateRange} criteria to search.
     */
    protected List<DateRange> getDateRanges() {
        return new ArrayList<DateRange>();
    }

    /**
     * Override it in subclass in order to provide specific {@link NullRestriction} criteria in search.
     */
    protected List<NullRestriction> getNullRestrictions() {
        return new ArrayList<NullRestriction>();
    }

    /**
     * Copy this search form information to a new {@link SearchTemplate} and returns it.
     */
    public SearchTemplate toSearchTemplate() {
        // search meta parameters
        SearchTemplate searchTemplate = searchParameters.toSearchTemplate();

        // date ranges
        searchTemplate.setDateRanges(getDateRanges());

        // null/not null criterion
        for (NullRestriction nr : getNullRestrictions()) {
            if (nr.getRestriction() == IS_NULL) {
                searchTemplate.addCriterion(isNull(nr.getProperty()));
            } else if (nr.getRestriction() == IS_NOT_NULL) {
                searchTemplate.addCriterion(isNotNull(nr.getProperty()));
            }
        }
        return searchTemplate;
    }
}