/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/manager/Manager.e.vm.java
 */
package com.bizintelapps.zytoon.service;

import com.bizintelapps.zytoon.dao.support.SearchTemplate;
import com.bizintelapps.zytoon.domain.Program;
import java.util.List;

/**
 * The ProgramService is a data-centric service for the {@link Program} entity.
 * It provides the expected methods to get/delete a {@link Program} instance
 * plus some methods to perform searches.
 * <p>
 * Search logic is driven by 2 kinds of parameters: a {@link Program} instance used
 * as a properties holder against which the search will be performed and a {@link SearchTemplate}
 * instance from where you can control your search options including the usage
 * of named queries.
 */
public interface ProgramService {
    
    List<Program> getEligiblePrograms(String username);
    
    void updateExpiredPrograms();
    
    void programCeationJob();
    
    void activateDueReports();

    void notifyDueReports();
    
    void notifyNonEnrolledUsers();
}
