/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/manager/Manager.e.vm.java
 */
package com.bizintelapps.zytoon.service;

import com.bizintelapps.zytoon.dao.support.SearchTemplate;
import com.bizintelapps.zytoon.domain.UserBasic;
import com.bizintelapps.zytoon.domain.UserProfile;
import com.bizintelapps.zytoon.domain.Users;

/**
 * The UsersService is a data-centric service for the {@link Users} entity.
 * It provides the expected methods to get/delete a {@link Users} instance
 * plus some methods to perform searches.
 * <p>
 * Search logic is driven by 2 kinds of parameters: a {@link Users} instance used
 * as a properties holder against which the search will be performed and a {@link SearchTemplate}
 * instance from where you can control your search options including the usage
 * of named queries.
 */
public interface UsersService {

    void emailAccessCode(String email);

    void resetPassword(String email, String accessCode, String password, String cPassword);

    Users getUsersByUsername(String email);

    void save(UserProfile userProfile);

    UserProfile findByUsername(String username);
    
    UserProfile findByUserProfileId(Integer id);

    void signUp(String fullname, String username, String password, String confirmPassword, String ip);

    UserBasic getUserBasicByUserProfileId(Integer userProfileId);
    
    UserBasic findUserBasicByUsername(String username);

    UserBasic getUserBasicById(Integer user);
    
    void fbAccessToken(String accessToken, String ip);
}