/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/manager/Manager.e.vm.java
 */
package com.bizintelapps.zytoon.service;

import com.bizintelapps.zytoon.dao.support.SearchTemplate;
import com.bizintelapps.zytoon.domain.Program;
import com.bizintelapps.zytoon.domain.Report;
import com.bizintelapps.zytoon.domain.ReportDto;
import com.bizintelapps.zytoon.domain.UserEnrollment;
import java.util.List;

/**
 * The UserEnrollmentService is a data-centric service for the {@link UserEnrollment} entity.
 * It provides the expected methods to get/delete a {@link UserEnrollment} instance
 * plus some methods to perform searches.
 * <p>
 * Search logic is driven by 2 kinds of parameters: a {@link UserEnrollment} instance used
 * as a properties holder against which the search will be performed and a {@link SearchTemplate}
 * instance from where you can control your search options including the usage
 * of named queries.
 */
public interface UserEnrollmentService {

    void saveReport(Report report);

    List<UserEnrollment> getActiveEnrollments();

//    SalahReport getByEnrollment(Integer id);
    List<UserEnrollment> getDueEnrollments(Integer userId);

//    List<SalahReport> getByEnrollmentId(Integer id, Boolean isDue);
    Report getReportById(Integer id);

    void enroll(Integer programId, String username);

    String submitSalah(Integer reportId, Integer fajr, Integer zuhr, Integer asr,
            Integer magrib, Integer isha, Boolean isSubmitted, String username);

    String submitFood(Integer reportId, Integer breakfast, Integer lunch,
            Integer dinner, Boolean isSubmitted, String username);

    List<ReportDto> getReports(String username);

    List<Program> getMyEnrollments(String username);

    public String submitOneRuleProgram(Integer reportId, int yes, String username);
}
