/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/manager/Manager.e.vm.java
 */
package com.bizintelapps.zytoon.service;

import com.bizintelapps.zytoon.domain.Book;
import com.bizintelapps.zytoon.domain.Users;
import java.util.List;

/**
 * The UsersService is a data-centric service for the {@link Users} entity.
 * It provides the expected methods to get/delete a {@link Users} instance
 * plus some methods to perform searches.
 * <p>
 * Search logic is driven by 2 kinds of parameters: a {@link Users} instance used
 * as a properties holder against which the search will be performed and a {@link SearchTemplate}
 * instance from where you can control your search options including the usage
 * of named queries.
 */
public interface WallService {
    void addBook(String title, String url, String username, String ip);
    List<Book> getBooks(int startPosition, int maxResults);
    void awesomeBook(Integer bookId, String username);
    List<Book> myBooks(String username);
}