/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/formatter/Formatter.e.vm.java
 */
package com.bizintelapps.zytoon.formatter;

import java.text.ParseException;
import java.util.Locale;

import com.bizintelapps.zytoon.domain.Users;
import com.bizintelapps.zytoon.service.UsersService;
import com.bizintelapps.zytoon.formatter.support.DiscoverableFormatter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * {@link Formatter} for {@link Users} that is picked by automatically by {@link CustomFormattingConversionServiceFactory}
 * 
 * @see Formatter
 * @see CustomFormattingConversionServiceFactory
 */
@Component
public class UsersFormatter implements DiscoverableFormatter<Users> {

    @Autowired
    private UsersService usersService;

    @Override
    public Class<Users> getTarget() {
        return Users.class;
    }

    @Override
    public String print(Users users, Locale locale) {
        if (users == null) {
            return "";
        }

        StringBuilder sb = new StringBuilder();
        // make a nice display string here...

        if (users.getPassword() != null) {
            sb.append(users.getPassword()).append(" ");
        }

        if (sb.length() > 0) {
            return sb.toString();
        } else if (users.isPrimaryKeySet()) {
            return users.getPrimaryKey();
        } else {
            return users.toString();
        }
    }

    @Override
    public Users parse(String text, Locale locale) throws ParseException {
        if (text == null || text.isEmpty()) {
            return new Users();
        }
        Users users = usersService.getUsersByUsername(text);
        return users != null ? users : new Users();
    }
}
